twitter:
  twitter_api_key: '9IhC8jmWzOk8m47olREcoowyx'
  twitter_api_secret: 'bmsgfuNz0CzNMu8G1GYiyGYuIuwAPODyZJPX00rMDxybIsrCRN'

facebook:
 facebook_api_key: "4394409730620012"
 facebook_api_secret: "cac8310586d86220"

google_oauth2:
 google_api_key: "833699845780-ffgq5g3b0628d9bm2f1s27p5hk44p7h9.apps.googleusercontent.com"
 google_api_secret: "Ah5cxCMhiM7dMO_SR8CHwIFT"
